repos:
  - repo: https://github.com/ambv/black
    rev: 21.10b0
    hooks:
      - id: black
        language_version: python3.9
        args: ['.']
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies: [flake8-blind-except, flake8-bugbear, flake8-comprehensions,
          flake8-debugger, flake8-docstrings, flake8-isort, flake8-polyfill, flake8-pytest,
          flake8-quotes, yesqa]
        language_version: python3.9
        args: ['--config=.flake8']