version: "3.7"

volumes:
  base_data:
    name: "base_data"

networks:
  base_network:
    driver: bridge

services:
  base:
    container_name: base_app
    image: base_app_image
    build: .
    volumes:
      - base_data:/app
    ports:
      - "5000:5000"
    expose:
      - "5000"
    environment:
      PORT: 5000
      FLASK_ENV: production
    networks:
      - base_network