version: "3.7"

services:
  base:
    container_name: base_app
    image: base_app_image
    build:
      context: ..
      dockerfile: .docker/Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - "5000:5000"